channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - lightgbm==3.3.2
      - scikit-learn==0.24.2
      - pandas==1.4.1
      - numpy==1.22.2
      - ipykernel
      - matplotlib==3.3.4
      - cloudpickle
      - mlflow==1.23.1
      - azureml-sdk
      - azureml-mlflow
      - azureml-opendatasets
  - pip
name: lightgbm-python-env